name: pocket-js-server

services:
  postgres:
    image: bitnami/postgresql:13.16.0
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: "inorbit"
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"
